### ISSUE TITLE
Connect API to MongoDB

### ISSUE THREAD

**Issue by tomlenbzh** [tomlenbzh/nest-mongo-api#1]
### Tasks
- [x] Install [@nestjs/mongoose](https://www.npmjs.com/package/@nestjs/mongoose) for DB management
- [x] Install [@nestjs/config](https://www.npmjs.com/package/@nestjs/config) to access env variables
- [x] Inject `ConfigModule` in `app.module.ts`
- [x] Inject `MongooseModule` in `app.module.ts`

### Expected outcome:
A live mongoDB connection should be established on API startup
